// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module AddStreams (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in1_V_V_dout,
        in1_V_V_empty_n,
        in1_V_V_read,
        in2_V_V_dout,
        in2_V_V_empty_n,
        in2_V_V_read,
        out_V_V_din,
        out_V_V_full_n,
        out_V_V_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state5 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [127:0] in1_V_V_dout;
input   in1_V_V_empty_n;
output   in1_V_V_read;
input  [127:0] in2_V_V_dout;
input   in2_V_V_empty_n;
output   in2_V_V_read;
output  [127:0] out_V_V_din;
input   out_V_V_full_n;
output   out_V_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in1_V_V_read;
reg in2_V_V_read;
reg out_V_V_write;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    in1_V_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln675_reg_2811;
reg    in2_V_V_blk_n;
reg    out_V_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] icmp_ln675_reg_2811_pp0_iter1_reg;
reg   [2:0] i_0_reg_235;
wire   [0:0] icmp_ln675_fu_246_p2;
wire    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_state4_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [2:0] i_fu_252_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [3:0] add_ln703_fu_296_p2;
reg   [3:0] add_ln703_reg_2820;
reg   [1:0] tmp_1_reg_2825;
wire   [3:0] add_ln703_1_fu_362_p2;
reg   [3:0] add_ln703_1_reg_2830;
reg   [1:0] tmp_2_reg_2835;
wire   [3:0] add_ln703_2_fu_428_p2;
reg   [3:0] add_ln703_2_reg_2840;
reg   [1:0] tmp_3_reg_2845;
wire   [3:0] add_ln703_3_fu_494_p2;
reg   [3:0] add_ln703_3_reg_2850;
reg   [1:0] tmp_4_reg_2855;
wire   [3:0] add_ln703_4_fu_560_p2;
reg   [3:0] add_ln703_4_reg_2860;
reg   [1:0] tmp_5_reg_2865;
wire   [3:0] add_ln703_5_fu_626_p2;
reg   [3:0] add_ln703_5_reg_2870;
reg   [1:0] tmp_6_reg_2875;
wire   [3:0] add_ln703_6_fu_692_p2;
reg   [3:0] add_ln703_6_reg_2880;
reg   [1:0] tmp_7_reg_2885;
wire   [3:0] add_ln703_7_fu_758_p2;
reg   [3:0] add_ln703_7_reg_2890;
reg   [1:0] tmp_8_reg_2895;
wire   [3:0] add_ln703_8_fu_824_p2;
reg   [3:0] add_ln703_8_reg_2900;
reg   [1:0] tmp_9_reg_2905;
wire   [3:0] add_ln703_9_fu_890_p2;
reg   [3:0] add_ln703_9_reg_2910;
reg   [1:0] tmp_s_reg_2915;
wire   [3:0] add_ln703_10_fu_956_p2;
reg   [3:0] add_ln703_10_reg_2920;
reg   [1:0] tmp_10_reg_2925;
wire   [3:0] add_ln703_11_fu_1022_p2;
reg   [3:0] add_ln703_11_reg_2930;
reg   [1:0] tmp_11_reg_2935;
wire   [3:0] add_ln703_12_fu_1088_p2;
reg   [3:0] add_ln703_12_reg_2940;
reg   [1:0] tmp_12_reg_2945;
wire   [3:0] add_ln703_13_fu_1154_p2;
reg   [3:0] add_ln703_13_reg_2950;
reg   [1:0] tmp_13_reg_2955;
wire   [3:0] add_ln703_14_fu_1220_p2;
reg   [3:0] add_ln703_14_reg_2960;
reg   [1:0] tmp_14_reg_2965;
wire   [3:0] add_ln703_15_fu_1286_p2;
reg   [3:0] add_ln703_15_reg_2970;
reg   [1:0] tmp_15_reg_2975;
wire   [3:0] add_ln703_16_fu_1352_p2;
reg   [3:0] add_ln703_16_reg_2980;
reg   [1:0] tmp_16_reg_2985;
wire   [3:0] add_ln703_17_fu_1418_p2;
reg   [3:0] add_ln703_17_reg_2990;
reg   [1:0] tmp_17_reg_2995;
wire   [3:0] add_ln703_18_fu_1484_p2;
reg   [3:0] add_ln703_18_reg_3000;
reg   [1:0] tmp_18_reg_3005;
wire   [3:0] add_ln703_19_fu_1550_p2;
reg   [3:0] add_ln703_19_reg_3010;
reg   [1:0] tmp_19_reg_3015;
wire   [3:0] add_ln703_20_fu_1616_p2;
reg   [3:0] add_ln703_20_reg_3020;
reg   [1:0] tmp_20_reg_3025;
wire   [3:0] add_ln703_21_fu_1682_p2;
reg   [3:0] add_ln703_21_reg_3030;
reg   [1:0] tmp_21_reg_3035;
wire   [3:0] add_ln703_22_fu_1748_p2;
reg   [3:0] add_ln703_22_reg_3040;
reg   [1:0] tmp_22_reg_3045;
wire   [3:0] add_ln703_23_fu_1814_p2;
reg   [3:0] add_ln703_23_reg_3050;
reg   [1:0] tmp_23_reg_3055;
wire   [3:0] add_ln703_24_fu_1880_p2;
reg   [3:0] add_ln703_24_reg_3060;
reg   [1:0] tmp_24_reg_3065;
wire   [3:0] add_ln703_25_fu_1946_p2;
reg   [3:0] add_ln703_25_reg_3070;
reg   [1:0] tmp_25_reg_3075;
wire   [3:0] add_ln703_26_fu_2012_p2;
reg   [3:0] add_ln703_26_reg_3080;
reg   [1:0] tmp_26_reg_3085;
wire   [3:0] add_ln703_27_fu_2078_p2;
reg   [3:0] add_ln703_27_reg_3090;
reg   [1:0] tmp_27_reg_3095;
wire   [3:0] add_ln703_28_fu_2144_p2;
reg   [3:0] add_ln703_28_reg_3100;
reg   [1:0] tmp_28_reg_3105;
wire   [3:0] add_ln703_29_fu_2210_p2;
reg   [3:0] add_ln703_29_reg_3110;
reg   [1:0] tmp_29_reg_3115;
wire   [3:0] add_ln703_30_fu_2276_p2;
reg   [3:0] add_ln703_30_reg_3120;
reg   [1:0] tmp_30_reg_3125;
wire   [3:0] add_ln703_31_fu_2342_p2;
reg   [3:0] add_ln703_31_reg_3130;
reg   [1:0] tmp_31_reg_3135;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_block_pp0_stage0_01001;
wire   [3:0] trunc_ln647_fu_258_p1;
wire   [3:0] trunc_ln647_1_fu_262_p1;
wire   [4:0] zext_ln215_fu_266_p1;
wire   [4:0] zext_ln215_1_fu_270_p1;
wire   [4:0] add_ln1353_fu_274_p2;
wire   [5:0] zext_ln1353_fu_280_p1;
wire   [3:0] add_ln703_32_fu_290_p2;
wire   [5:0] add_ln1353_1_fu_284_p2;
wire   [3:0] p_Result_s_fu_312_p4;
wire   [3:0] p_Result_1_1_fu_322_p4;
wire   [4:0] zext_ln215_2_fu_332_p1;
wire   [4:0] zext_ln215_3_fu_336_p1;
wire   [4:0] add_ln1353_2_fu_340_p2;
wire   [5:0] zext_ln1353_1_fu_346_p1;
wire   [3:0] add_ln703_33_fu_356_p2;
wire   [5:0] add_ln1353_3_fu_350_p2;
wire   [3:0] p_Result_4_fu_378_p4;
wire   [3:0] p_Result_1_2_fu_388_p4;
wire   [4:0] zext_ln215_4_fu_398_p1;
wire   [4:0] zext_ln215_5_fu_402_p1;
wire   [4:0] add_ln1353_4_fu_406_p2;
wire   [5:0] zext_ln1353_2_fu_412_p1;
wire   [3:0] add_ln703_34_fu_422_p2;
wire   [5:0] add_ln1353_5_fu_416_p2;
wire   [3:0] p_Result_3_fu_444_p4;
wire   [3:0] p_Result_1_3_fu_454_p4;
wire   [4:0] zext_ln215_6_fu_464_p1;
wire   [4:0] zext_ln215_7_fu_468_p1;
wire   [4:0] add_ln1353_6_fu_472_p2;
wire   [5:0] zext_ln1353_3_fu_478_p1;
wire   [3:0] add_ln703_35_fu_488_p2;
wire   [5:0] add_ln1353_7_fu_482_p2;
wire   [3:0] p_Result_2_fu_510_p4;
wire   [3:0] p_Result_1_4_fu_520_p4;
wire   [4:0] zext_ln215_8_fu_530_p1;
wire   [4:0] zext_ln215_9_fu_534_p1;
wire   [4:0] add_ln1353_8_fu_538_p2;
wire   [5:0] zext_ln1353_4_fu_544_p1;
wire   [3:0] add_ln703_36_fu_554_p2;
wire   [5:0] add_ln1353_9_fu_548_p2;
wire   [3:0] p_Result_5_fu_576_p4;
wire   [3:0] p_Result_1_5_fu_586_p4;
wire   [4:0] zext_ln215_10_fu_596_p1;
wire   [4:0] zext_ln215_11_fu_600_p1;
wire   [4:0] add_ln1353_10_fu_604_p2;
wire   [5:0] zext_ln1353_5_fu_610_p1;
wire   [3:0] add_ln703_37_fu_620_p2;
wire   [5:0] add_ln1353_11_fu_614_p2;
wire   [3:0] p_Result_6_fu_642_p4;
wire   [3:0] p_Result_1_6_fu_652_p4;
wire   [4:0] zext_ln215_12_fu_662_p1;
wire   [4:0] zext_ln215_13_fu_666_p1;
wire   [4:0] add_ln1353_12_fu_670_p2;
wire   [5:0] zext_ln1353_6_fu_676_p1;
wire   [3:0] add_ln703_38_fu_686_p2;
wire   [5:0] add_ln1353_13_fu_680_p2;
wire   [3:0] p_Result_7_fu_708_p4;
wire   [3:0] p_Result_1_7_fu_718_p4;
wire   [4:0] zext_ln215_14_fu_728_p1;
wire   [4:0] zext_ln215_15_fu_732_p1;
wire   [4:0] add_ln1353_14_fu_736_p2;
wire   [5:0] zext_ln1353_7_fu_742_p1;
wire   [3:0] add_ln703_39_fu_752_p2;
wire   [5:0] add_ln1353_15_fu_746_p2;
wire   [3:0] p_Result_8_fu_774_p4;
wire   [3:0] p_Result_1_8_fu_784_p4;
wire   [4:0] zext_ln215_16_fu_794_p1;
wire   [4:0] zext_ln215_17_fu_798_p1;
wire   [4:0] add_ln1353_16_fu_802_p2;
wire   [5:0] zext_ln1353_8_fu_808_p1;
wire   [3:0] add_ln703_40_fu_818_p2;
wire   [5:0] add_ln1353_17_fu_812_p2;
wire   [3:0] p_Result_9_fu_840_p4;
wire   [3:0] p_Result_1_9_fu_850_p4;
wire   [4:0] zext_ln215_18_fu_860_p1;
wire   [4:0] zext_ln215_19_fu_864_p1;
wire   [4:0] add_ln1353_18_fu_868_p2;
wire   [5:0] zext_ln1353_9_fu_874_p1;
wire   [3:0] add_ln703_41_fu_884_p2;
wire   [5:0] add_ln1353_19_fu_878_p2;
wire   [3:0] p_Result_1_fu_906_p4;
wire   [3:0] p_Result_1_s_fu_916_p4;
wire   [4:0] zext_ln215_20_fu_926_p1;
wire   [4:0] zext_ln215_21_fu_930_p1;
wire   [4:0] add_ln1353_20_fu_934_p2;
wire   [5:0] zext_ln1353_10_fu_940_p1;
wire   [3:0] add_ln703_42_fu_950_p2;
wire   [5:0] add_ln1353_21_fu_944_p2;
wire   [3:0] p_Result_10_fu_972_p4;
wire   [3:0] p_Result_1_10_fu_982_p4;
wire   [4:0] zext_ln215_22_fu_992_p1;
wire   [4:0] zext_ln215_23_fu_996_p1;
wire   [4:0] add_ln1353_22_fu_1000_p2;
wire   [5:0] zext_ln1353_11_fu_1006_p1;
wire   [3:0] add_ln703_43_fu_1016_p2;
wire   [5:0] add_ln1353_23_fu_1010_p2;
wire   [3:0] p_Result_11_fu_1038_p4;
wire   [3:0] p_Result_1_11_fu_1048_p4;
wire   [4:0] zext_ln215_24_fu_1058_p1;
wire   [4:0] zext_ln215_25_fu_1062_p1;
wire   [4:0] add_ln1353_24_fu_1066_p2;
wire   [5:0] zext_ln1353_12_fu_1072_p1;
wire   [3:0] add_ln703_44_fu_1082_p2;
wire   [5:0] add_ln1353_25_fu_1076_p2;
wire   [3:0] p_Result_12_fu_1104_p4;
wire   [3:0] p_Result_1_12_fu_1114_p4;
wire   [4:0] zext_ln215_26_fu_1124_p1;
wire   [4:0] zext_ln215_27_fu_1128_p1;
wire   [4:0] add_ln1353_26_fu_1132_p2;
wire   [5:0] zext_ln1353_13_fu_1138_p1;
wire   [3:0] add_ln703_45_fu_1148_p2;
wire   [5:0] add_ln1353_27_fu_1142_p2;
wire   [3:0] p_Result_13_fu_1170_p4;
wire   [3:0] p_Result_1_13_fu_1180_p4;
wire   [4:0] zext_ln215_28_fu_1190_p1;
wire   [4:0] zext_ln215_29_fu_1194_p1;
wire   [4:0] add_ln1353_28_fu_1198_p2;
wire   [5:0] zext_ln1353_14_fu_1204_p1;
wire   [3:0] add_ln703_46_fu_1214_p2;
wire   [5:0] add_ln1353_29_fu_1208_p2;
wire   [3:0] p_Result_14_fu_1236_p4;
wire   [3:0] p_Result_1_14_fu_1246_p4;
wire   [4:0] zext_ln215_30_fu_1256_p1;
wire   [4:0] zext_ln215_31_fu_1260_p1;
wire   [4:0] add_ln1353_30_fu_1264_p2;
wire   [5:0] zext_ln1353_15_fu_1270_p1;
wire   [3:0] add_ln703_47_fu_1280_p2;
wire   [5:0] add_ln1353_31_fu_1274_p2;
wire   [3:0] p_Result_15_fu_1302_p4;
wire   [3:0] p_Result_1_15_fu_1312_p4;
wire   [4:0] zext_ln215_32_fu_1322_p1;
wire   [4:0] zext_ln215_33_fu_1326_p1;
wire   [4:0] add_ln1353_32_fu_1330_p2;
wire   [5:0] zext_ln1353_16_fu_1336_p1;
wire   [3:0] add_ln703_48_fu_1346_p2;
wire   [5:0] add_ln1353_33_fu_1340_p2;
wire   [3:0] p_Result_16_fu_1368_p4;
wire   [3:0] p_Result_1_16_fu_1378_p4;
wire   [4:0] zext_ln215_34_fu_1388_p1;
wire   [4:0] zext_ln215_35_fu_1392_p1;
wire   [4:0] add_ln1353_34_fu_1396_p2;
wire   [5:0] zext_ln1353_17_fu_1402_p1;
wire   [3:0] add_ln703_49_fu_1412_p2;
wire   [5:0] add_ln1353_35_fu_1406_p2;
wire   [3:0] p_Result_17_fu_1434_p4;
wire   [3:0] p_Result_1_17_fu_1444_p4;
wire   [4:0] zext_ln215_36_fu_1454_p1;
wire   [4:0] zext_ln215_37_fu_1458_p1;
wire   [4:0] add_ln1353_36_fu_1462_p2;
wire   [5:0] zext_ln1353_18_fu_1468_p1;
wire   [3:0] add_ln703_50_fu_1478_p2;
wire   [5:0] add_ln1353_37_fu_1472_p2;
wire   [3:0] p_Result_18_fu_1500_p4;
wire   [3:0] p_Result_1_18_fu_1510_p4;
wire   [4:0] zext_ln215_38_fu_1520_p1;
wire   [4:0] zext_ln215_39_fu_1524_p1;
wire   [4:0] add_ln1353_38_fu_1528_p2;
wire   [5:0] zext_ln1353_19_fu_1534_p1;
wire   [3:0] add_ln703_51_fu_1544_p2;
wire   [5:0] add_ln1353_39_fu_1538_p2;
wire   [3:0] p_Result_19_fu_1566_p4;
wire   [3:0] p_Result_1_19_fu_1576_p4;
wire   [4:0] zext_ln215_40_fu_1586_p1;
wire   [4:0] zext_ln215_41_fu_1590_p1;
wire   [4:0] add_ln1353_40_fu_1594_p2;
wire   [5:0] zext_ln1353_20_fu_1600_p1;
wire   [3:0] add_ln703_52_fu_1610_p2;
wire   [5:0] add_ln1353_41_fu_1604_p2;
wire   [3:0] p_Result_20_fu_1632_p4;
wire   [3:0] p_Result_1_20_fu_1642_p4;
wire   [4:0] zext_ln215_42_fu_1652_p1;
wire   [4:0] zext_ln215_43_fu_1656_p1;
wire   [4:0] add_ln1353_42_fu_1660_p2;
wire   [5:0] zext_ln1353_21_fu_1666_p1;
wire   [3:0] add_ln703_53_fu_1676_p2;
wire   [5:0] add_ln1353_43_fu_1670_p2;
wire   [3:0] p_Result_21_fu_1698_p4;
wire   [3:0] p_Result_1_21_fu_1708_p4;
wire   [4:0] zext_ln215_44_fu_1718_p1;
wire   [4:0] zext_ln215_45_fu_1722_p1;
wire   [4:0] add_ln1353_44_fu_1726_p2;
wire   [5:0] zext_ln1353_22_fu_1732_p1;
wire   [3:0] add_ln703_54_fu_1742_p2;
wire   [5:0] add_ln1353_45_fu_1736_p2;
wire   [3:0] p_Result_22_fu_1764_p4;
wire   [3:0] p_Result_1_22_fu_1774_p4;
wire   [4:0] zext_ln215_46_fu_1784_p1;
wire   [4:0] zext_ln215_47_fu_1788_p1;
wire   [4:0] add_ln1353_46_fu_1792_p2;
wire   [5:0] zext_ln1353_23_fu_1798_p1;
wire   [3:0] add_ln703_55_fu_1808_p2;
wire   [5:0] add_ln1353_47_fu_1802_p2;
wire   [3:0] p_Result_23_fu_1830_p4;
wire   [3:0] p_Result_1_23_fu_1840_p4;
wire   [4:0] zext_ln215_48_fu_1850_p1;
wire   [4:0] zext_ln215_49_fu_1854_p1;
wire   [4:0] add_ln1353_48_fu_1858_p2;
wire   [5:0] zext_ln1353_24_fu_1864_p1;
wire   [3:0] add_ln703_56_fu_1874_p2;
wire   [5:0] add_ln1353_49_fu_1868_p2;
wire   [3:0] p_Result_24_fu_1896_p4;
wire   [3:0] p_Result_1_24_fu_1906_p4;
wire   [4:0] zext_ln215_50_fu_1916_p1;
wire   [4:0] zext_ln215_51_fu_1920_p1;
wire   [4:0] add_ln1353_50_fu_1924_p2;
wire   [5:0] zext_ln1353_25_fu_1930_p1;
wire   [3:0] add_ln703_57_fu_1940_p2;
wire   [5:0] add_ln1353_51_fu_1934_p2;
wire   [3:0] p_Result_25_fu_1962_p4;
wire   [3:0] p_Result_1_25_fu_1972_p4;
wire   [4:0] zext_ln215_52_fu_1982_p1;
wire   [4:0] zext_ln215_53_fu_1986_p1;
wire   [4:0] add_ln1353_52_fu_1990_p2;
wire   [5:0] zext_ln1353_26_fu_1996_p1;
wire   [3:0] add_ln703_58_fu_2006_p2;
wire   [5:0] add_ln1353_53_fu_2000_p2;
wire   [3:0] p_Result_26_fu_2028_p4;
wire   [3:0] p_Result_1_26_fu_2038_p4;
wire   [4:0] zext_ln215_54_fu_2048_p1;
wire   [4:0] zext_ln215_55_fu_2052_p1;
wire   [4:0] add_ln1353_54_fu_2056_p2;
wire   [5:0] zext_ln1353_27_fu_2062_p1;
wire   [3:0] add_ln703_59_fu_2072_p2;
wire   [5:0] add_ln1353_55_fu_2066_p2;
wire   [3:0] p_Result_27_fu_2094_p4;
wire   [3:0] p_Result_1_27_fu_2104_p4;
wire   [4:0] zext_ln215_56_fu_2114_p1;
wire   [4:0] zext_ln215_57_fu_2118_p1;
wire   [4:0] add_ln1353_56_fu_2122_p2;
wire   [5:0] zext_ln1353_28_fu_2128_p1;
wire   [3:0] add_ln703_60_fu_2138_p2;
wire   [5:0] add_ln1353_57_fu_2132_p2;
wire   [3:0] p_Result_28_fu_2160_p4;
wire   [3:0] p_Result_1_28_fu_2170_p4;
wire   [4:0] zext_ln215_58_fu_2180_p1;
wire   [4:0] zext_ln215_59_fu_2184_p1;
wire   [4:0] add_ln1353_58_fu_2188_p2;
wire   [5:0] zext_ln1353_29_fu_2194_p1;
wire   [3:0] add_ln703_61_fu_2204_p2;
wire   [5:0] add_ln1353_59_fu_2198_p2;
wire   [3:0] p_Result_29_fu_2226_p4;
wire   [3:0] p_Result_1_29_fu_2236_p4;
wire   [4:0] zext_ln215_60_fu_2246_p1;
wire   [4:0] zext_ln215_61_fu_2250_p1;
wire   [4:0] add_ln1353_60_fu_2254_p2;
wire   [5:0] zext_ln1353_30_fu_2260_p1;
wire   [3:0] add_ln703_62_fu_2270_p2;
wire   [5:0] add_ln1353_61_fu_2264_p2;
wire   [3:0] p_Result_30_fu_2292_p4;
wire   [3:0] p_Result_1_30_fu_2302_p4;
wire   [4:0] zext_ln215_62_fu_2312_p1;
wire   [4:0] zext_ln215_63_fu_2316_p1;
wire   [4:0] add_ln1353_62_fu_2320_p2;
wire   [5:0] zext_ln1353_31_fu_2326_p1;
wire   [3:0] add_ln703_63_fu_2336_p2;
wire   [5:0] add_ln1353_63_fu_2330_p2;
wire   [0:0] icmp_ln785_fu_2358_p2;
wire   [0:0] icmp_ln785_1_fu_2370_p2;
wire   [0:0] icmp_ln785_2_fu_2382_p2;
wire   [0:0] icmp_ln785_3_fu_2394_p2;
wire   [0:0] icmp_ln785_4_fu_2406_p2;
wire   [0:0] icmp_ln785_5_fu_2418_p2;
wire   [0:0] icmp_ln785_6_fu_2430_p2;
wire   [0:0] icmp_ln785_7_fu_2442_p2;
wire   [0:0] icmp_ln785_8_fu_2454_p2;
wire   [0:0] icmp_ln785_9_fu_2466_p2;
wire   [0:0] icmp_ln785_10_fu_2478_p2;
wire   [0:0] icmp_ln785_11_fu_2490_p2;
wire   [0:0] icmp_ln785_12_fu_2502_p2;
wire   [0:0] icmp_ln785_13_fu_2514_p2;
wire   [0:0] icmp_ln785_14_fu_2526_p2;
wire   [0:0] icmp_ln785_15_fu_2538_p2;
wire   [0:0] icmp_ln785_16_fu_2550_p2;
wire   [0:0] icmp_ln785_17_fu_2562_p2;
wire   [0:0] icmp_ln785_18_fu_2574_p2;
wire   [0:0] icmp_ln785_19_fu_2586_p2;
wire   [0:0] icmp_ln785_20_fu_2598_p2;
wire   [0:0] icmp_ln785_21_fu_2610_p2;
wire   [0:0] icmp_ln785_22_fu_2622_p2;
wire   [0:0] icmp_ln785_23_fu_2634_p2;
wire   [0:0] icmp_ln785_24_fu_2646_p2;
wire   [0:0] icmp_ln785_25_fu_2658_p2;
wire   [0:0] icmp_ln785_26_fu_2670_p2;
wire   [0:0] icmp_ln785_27_fu_2682_p2;
wire   [0:0] icmp_ln785_28_fu_2694_p2;
wire   [0:0] icmp_ln785_29_fu_2706_p2;
wire   [0:0] icmp_ln785_30_fu_2718_p2;
wire   [0:0] icmp_ln785_31_fu_2730_p2;
wire   [3:0] select_ln340_31_fu_2735_p3;
wire   [3:0] select_ln340_30_fu_2723_p3;
wire   [3:0] select_ln340_29_fu_2711_p3;
wire   [3:0] select_ln340_28_fu_2699_p3;
wire   [3:0] select_ln340_27_fu_2687_p3;
wire   [3:0] select_ln340_26_fu_2675_p3;
wire   [3:0] select_ln340_25_fu_2663_p3;
wire   [3:0] select_ln340_24_fu_2651_p3;
wire   [3:0] select_ln340_23_fu_2639_p3;
wire   [3:0] select_ln340_22_fu_2627_p3;
wire   [3:0] select_ln340_21_fu_2615_p3;
wire   [3:0] select_ln340_20_fu_2603_p3;
wire   [3:0] select_ln340_19_fu_2591_p3;
wire   [3:0] select_ln340_18_fu_2579_p3;
wire   [3:0] select_ln340_17_fu_2567_p3;
wire   [3:0] select_ln340_16_fu_2555_p3;
wire   [3:0] select_ln340_15_fu_2543_p3;
wire   [3:0] select_ln340_14_fu_2531_p3;
wire   [3:0] select_ln340_13_fu_2519_p3;
wire   [3:0] select_ln340_12_fu_2507_p3;
wire   [3:0] select_ln340_11_fu_2495_p3;
wire   [3:0] select_ln340_10_fu_2483_p3;
wire   [3:0] select_ln340_9_fu_2471_p3;
wire   [3:0] select_ln340_8_fu_2459_p3;
wire   [3:0] select_ln340_7_fu_2447_p3;
wire   [3:0] select_ln340_6_fu_2435_p3;
wire   [3:0] select_ln340_5_fu_2423_p3;
wire   [3:0] select_ln340_4_fu_2411_p3;
wire   [3:0] select_ln340_3_fu_2399_p3;
wire   [3:0] select_ln340_2_fu_2387_p3;
wire   [3:0] select_ln340_1_fu_2375_p3;
wire   [3:0] select_ln340_fu_2363_p3;
wire    ap_CS_fsm_state5;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln675_fu_246_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_0_reg_235 <= i_fu_252_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_0_reg_235 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln675_reg_2811 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln703_10_reg_2920 <= add_ln703_10_fu_956_p2;
        add_ln703_11_reg_2930 <= add_ln703_11_fu_1022_p2;
        add_ln703_12_reg_2940 <= add_ln703_12_fu_1088_p2;
        add_ln703_13_reg_2950 <= add_ln703_13_fu_1154_p2;
        add_ln703_14_reg_2960 <= add_ln703_14_fu_1220_p2;
        add_ln703_15_reg_2970 <= add_ln703_15_fu_1286_p2;
        add_ln703_16_reg_2980 <= add_ln703_16_fu_1352_p2;
        add_ln703_17_reg_2990 <= add_ln703_17_fu_1418_p2;
        add_ln703_18_reg_3000 <= add_ln703_18_fu_1484_p2;
        add_ln703_19_reg_3010 <= add_ln703_19_fu_1550_p2;
        add_ln703_1_reg_2830 <= add_ln703_1_fu_362_p2;
        add_ln703_20_reg_3020 <= add_ln703_20_fu_1616_p2;
        add_ln703_21_reg_3030 <= add_ln703_21_fu_1682_p2;
        add_ln703_22_reg_3040 <= add_ln703_22_fu_1748_p2;
        add_ln703_23_reg_3050 <= add_ln703_23_fu_1814_p2;
        add_ln703_24_reg_3060 <= add_ln703_24_fu_1880_p2;
        add_ln703_25_reg_3070 <= add_ln703_25_fu_1946_p2;
        add_ln703_26_reg_3080 <= add_ln703_26_fu_2012_p2;
        add_ln703_27_reg_3090 <= add_ln703_27_fu_2078_p2;
        add_ln703_28_reg_3100 <= add_ln703_28_fu_2144_p2;
        add_ln703_29_reg_3110 <= add_ln703_29_fu_2210_p2;
        add_ln703_2_reg_2840 <= add_ln703_2_fu_428_p2;
        add_ln703_30_reg_3120 <= add_ln703_30_fu_2276_p2;
        add_ln703_31_reg_3130 <= add_ln703_31_fu_2342_p2;
        add_ln703_3_reg_2850 <= add_ln703_3_fu_494_p2;
        add_ln703_4_reg_2860 <= add_ln703_4_fu_560_p2;
        add_ln703_5_reg_2870 <= add_ln703_5_fu_626_p2;
        add_ln703_6_reg_2880 <= add_ln703_6_fu_692_p2;
        add_ln703_7_reg_2890 <= add_ln703_7_fu_758_p2;
        add_ln703_8_reg_2900 <= add_ln703_8_fu_824_p2;
        add_ln703_9_reg_2910 <= add_ln703_9_fu_890_p2;
        add_ln703_reg_2820 <= add_ln703_fu_296_p2;
        tmp_10_reg_2925 <= {{add_ln1353_21_fu_944_p2[5:4]}};
        tmp_11_reg_2935 <= {{add_ln1353_23_fu_1010_p2[5:4]}};
        tmp_12_reg_2945 <= {{add_ln1353_25_fu_1076_p2[5:4]}};
        tmp_13_reg_2955 <= {{add_ln1353_27_fu_1142_p2[5:4]}};
        tmp_14_reg_2965 <= {{add_ln1353_29_fu_1208_p2[5:4]}};
        tmp_15_reg_2975 <= {{add_ln1353_31_fu_1274_p2[5:4]}};
        tmp_16_reg_2985 <= {{add_ln1353_33_fu_1340_p2[5:4]}};
        tmp_17_reg_2995 <= {{add_ln1353_35_fu_1406_p2[5:4]}};
        tmp_18_reg_3005 <= {{add_ln1353_37_fu_1472_p2[5:4]}};
        tmp_19_reg_3015 <= {{add_ln1353_39_fu_1538_p2[5:4]}};
        tmp_1_reg_2825 <= {{add_ln1353_1_fu_284_p2[5:4]}};
        tmp_20_reg_3025 <= {{add_ln1353_41_fu_1604_p2[5:4]}};
        tmp_21_reg_3035 <= {{add_ln1353_43_fu_1670_p2[5:4]}};
        tmp_22_reg_3045 <= {{add_ln1353_45_fu_1736_p2[5:4]}};
        tmp_23_reg_3055 <= {{add_ln1353_47_fu_1802_p2[5:4]}};
        tmp_24_reg_3065 <= {{add_ln1353_49_fu_1868_p2[5:4]}};
        tmp_25_reg_3075 <= {{add_ln1353_51_fu_1934_p2[5:4]}};
        tmp_26_reg_3085 <= {{add_ln1353_53_fu_2000_p2[5:4]}};
        tmp_27_reg_3095 <= {{add_ln1353_55_fu_2066_p2[5:4]}};
        tmp_28_reg_3105 <= {{add_ln1353_57_fu_2132_p2[5:4]}};
        tmp_29_reg_3115 <= {{add_ln1353_59_fu_2198_p2[5:4]}};
        tmp_2_reg_2835 <= {{add_ln1353_3_fu_350_p2[5:4]}};
        tmp_30_reg_3125 <= {{add_ln1353_61_fu_2264_p2[5:4]}};
        tmp_31_reg_3135 <= {{add_ln1353_63_fu_2330_p2[5:4]}};
        tmp_3_reg_2845 <= {{add_ln1353_5_fu_416_p2[5:4]}};
        tmp_4_reg_2855 <= {{add_ln1353_7_fu_482_p2[5:4]}};
        tmp_5_reg_2865 <= {{add_ln1353_9_fu_548_p2[5:4]}};
        tmp_6_reg_2875 <= {{add_ln1353_11_fu_614_p2[5:4]}};
        tmp_7_reg_2885 <= {{add_ln1353_13_fu_680_p2[5:4]}};
        tmp_8_reg_2895 <= {{add_ln1353_15_fu_746_p2[5:4]}};
        tmp_9_reg_2905 <= {{add_ln1353_17_fu_812_p2[5:4]}};
        tmp_s_reg_2915 <= {{add_ln1353_19_fu_878_p2[5:4]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln675_reg_2811 <= icmp_ln675_fu_246_p2;
        icmp_ln675_reg_2811_pp0_iter1_reg <= icmp_ln675_reg_2811;
    end
end

always @ (*) begin
    if ((icmp_ln675_fu_246_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln675_reg_2811 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in1_V_V_blk_n = in1_V_V_empty_n;
    end else begin
        in1_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln675_reg_2811 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in1_V_V_read = 1'b1;
    end else begin
        in1_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln675_reg_2811 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in2_V_V_blk_n = in2_V_V_empty_n;
    end else begin
        in2_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln675_reg_2811 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in2_V_V_read = 1'b1;
    end else begin
        in2_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln675_reg_2811_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        out_V_V_blk_n = out_V_V_full_n;
    end else begin
        out_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln675_reg_2811_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        out_V_V_write = 1'b1;
    end else begin
        out_V_V_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln675_fu_246_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((icmp_ln675_fu_246_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1353_10_fu_604_p2 = (zext_ln215_10_fu_596_p1 + zext_ln215_11_fu_600_p1);

assign add_ln1353_11_fu_614_p2 = (6'd2 + zext_ln1353_5_fu_610_p1);

assign add_ln1353_12_fu_670_p2 = (zext_ln215_12_fu_662_p1 + zext_ln215_13_fu_666_p1);

assign add_ln1353_13_fu_680_p2 = (6'd2 + zext_ln1353_6_fu_676_p1);

assign add_ln1353_14_fu_736_p2 = (zext_ln215_14_fu_728_p1 + zext_ln215_15_fu_732_p1);

assign add_ln1353_15_fu_746_p2 = (6'd2 + zext_ln1353_7_fu_742_p1);

assign add_ln1353_16_fu_802_p2 = (zext_ln215_16_fu_794_p1 + zext_ln215_17_fu_798_p1);

assign add_ln1353_17_fu_812_p2 = (6'd2 + zext_ln1353_8_fu_808_p1);

assign add_ln1353_18_fu_868_p2 = (zext_ln215_18_fu_860_p1 + zext_ln215_19_fu_864_p1);

assign add_ln1353_19_fu_878_p2 = (6'd2 + zext_ln1353_9_fu_874_p1);

assign add_ln1353_1_fu_284_p2 = (6'd2 + zext_ln1353_fu_280_p1);

assign add_ln1353_20_fu_934_p2 = (zext_ln215_20_fu_926_p1 + zext_ln215_21_fu_930_p1);

assign add_ln1353_21_fu_944_p2 = (6'd2 + zext_ln1353_10_fu_940_p1);

assign add_ln1353_22_fu_1000_p2 = (zext_ln215_22_fu_992_p1 + zext_ln215_23_fu_996_p1);

assign add_ln1353_23_fu_1010_p2 = (6'd2 + zext_ln1353_11_fu_1006_p1);

assign add_ln1353_24_fu_1066_p2 = (zext_ln215_24_fu_1058_p1 + zext_ln215_25_fu_1062_p1);

assign add_ln1353_25_fu_1076_p2 = (6'd2 + zext_ln1353_12_fu_1072_p1);

assign add_ln1353_26_fu_1132_p2 = (zext_ln215_26_fu_1124_p1 + zext_ln215_27_fu_1128_p1);

assign add_ln1353_27_fu_1142_p2 = (6'd2 + zext_ln1353_13_fu_1138_p1);

assign add_ln1353_28_fu_1198_p2 = (zext_ln215_28_fu_1190_p1 + zext_ln215_29_fu_1194_p1);

assign add_ln1353_29_fu_1208_p2 = (6'd2 + zext_ln1353_14_fu_1204_p1);

assign add_ln1353_2_fu_340_p2 = (zext_ln215_2_fu_332_p1 + zext_ln215_3_fu_336_p1);

assign add_ln1353_30_fu_1264_p2 = (zext_ln215_30_fu_1256_p1 + zext_ln215_31_fu_1260_p1);

assign add_ln1353_31_fu_1274_p2 = (6'd2 + zext_ln1353_15_fu_1270_p1);

assign add_ln1353_32_fu_1330_p2 = (zext_ln215_32_fu_1322_p1 + zext_ln215_33_fu_1326_p1);

assign add_ln1353_33_fu_1340_p2 = (6'd2 + zext_ln1353_16_fu_1336_p1);

assign add_ln1353_34_fu_1396_p2 = (zext_ln215_34_fu_1388_p1 + zext_ln215_35_fu_1392_p1);

assign add_ln1353_35_fu_1406_p2 = (6'd2 + zext_ln1353_17_fu_1402_p1);

assign add_ln1353_36_fu_1462_p2 = (zext_ln215_36_fu_1454_p1 + zext_ln215_37_fu_1458_p1);

assign add_ln1353_37_fu_1472_p2 = (6'd2 + zext_ln1353_18_fu_1468_p1);

assign add_ln1353_38_fu_1528_p2 = (zext_ln215_38_fu_1520_p1 + zext_ln215_39_fu_1524_p1);

assign add_ln1353_39_fu_1538_p2 = (6'd2 + zext_ln1353_19_fu_1534_p1);

assign add_ln1353_3_fu_350_p2 = (6'd2 + zext_ln1353_1_fu_346_p1);

assign add_ln1353_40_fu_1594_p2 = (zext_ln215_40_fu_1586_p1 + zext_ln215_41_fu_1590_p1);

assign add_ln1353_41_fu_1604_p2 = (6'd2 + zext_ln1353_20_fu_1600_p1);

assign add_ln1353_42_fu_1660_p2 = (zext_ln215_42_fu_1652_p1 + zext_ln215_43_fu_1656_p1);

assign add_ln1353_43_fu_1670_p2 = (6'd2 + zext_ln1353_21_fu_1666_p1);

assign add_ln1353_44_fu_1726_p2 = (zext_ln215_44_fu_1718_p1 + zext_ln215_45_fu_1722_p1);

assign add_ln1353_45_fu_1736_p2 = (6'd2 + zext_ln1353_22_fu_1732_p1);

assign add_ln1353_46_fu_1792_p2 = (zext_ln215_46_fu_1784_p1 + zext_ln215_47_fu_1788_p1);

assign add_ln1353_47_fu_1802_p2 = (6'd2 + zext_ln1353_23_fu_1798_p1);

assign add_ln1353_48_fu_1858_p2 = (zext_ln215_48_fu_1850_p1 + zext_ln215_49_fu_1854_p1);

assign add_ln1353_49_fu_1868_p2 = (6'd2 + zext_ln1353_24_fu_1864_p1);

assign add_ln1353_4_fu_406_p2 = (zext_ln215_4_fu_398_p1 + zext_ln215_5_fu_402_p1);

assign add_ln1353_50_fu_1924_p2 = (zext_ln215_50_fu_1916_p1 + zext_ln215_51_fu_1920_p1);

assign add_ln1353_51_fu_1934_p2 = (6'd2 + zext_ln1353_25_fu_1930_p1);

assign add_ln1353_52_fu_1990_p2 = (zext_ln215_52_fu_1982_p1 + zext_ln215_53_fu_1986_p1);

assign add_ln1353_53_fu_2000_p2 = (6'd2 + zext_ln1353_26_fu_1996_p1);

assign add_ln1353_54_fu_2056_p2 = (zext_ln215_54_fu_2048_p1 + zext_ln215_55_fu_2052_p1);

assign add_ln1353_55_fu_2066_p2 = (6'd2 + zext_ln1353_27_fu_2062_p1);

assign add_ln1353_56_fu_2122_p2 = (zext_ln215_56_fu_2114_p1 + zext_ln215_57_fu_2118_p1);

assign add_ln1353_57_fu_2132_p2 = (6'd2 + zext_ln1353_28_fu_2128_p1);

assign add_ln1353_58_fu_2188_p2 = (zext_ln215_58_fu_2180_p1 + zext_ln215_59_fu_2184_p1);

assign add_ln1353_59_fu_2198_p2 = (6'd2 + zext_ln1353_29_fu_2194_p1);

assign add_ln1353_5_fu_416_p2 = (6'd2 + zext_ln1353_2_fu_412_p1);

assign add_ln1353_60_fu_2254_p2 = (zext_ln215_60_fu_2246_p1 + zext_ln215_61_fu_2250_p1);

assign add_ln1353_61_fu_2264_p2 = (6'd2 + zext_ln1353_30_fu_2260_p1);

assign add_ln1353_62_fu_2320_p2 = (zext_ln215_62_fu_2312_p1 + zext_ln215_63_fu_2316_p1);

assign add_ln1353_63_fu_2330_p2 = (6'd2 + zext_ln1353_31_fu_2326_p1);

assign add_ln1353_6_fu_472_p2 = (zext_ln215_6_fu_464_p1 + zext_ln215_7_fu_468_p1);

assign add_ln1353_7_fu_482_p2 = (6'd2 + zext_ln1353_3_fu_478_p1);

assign add_ln1353_8_fu_538_p2 = (zext_ln215_8_fu_530_p1 + zext_ln215_9_fu_534_p1);

assign add_ln1353_9_fu_548_p2 = (6'd2 + zext_ln1353_4_fu_544_p1);

assign add_ln1353_fu_274_p2 = (zext_ln215_fu_266_p1 + zext_ln215_1_fu_270_p1);

assign add_ln703_10_fu_956_p2 = (add_ln703_42_fu_950_p2 + p_Result_1_s_fu_916_p4);

assign add_ln703_11_fu_1022_p2 = (add_ln703_43_fu_1016_p2 + p_Result_1_10_fu_982_p4);

assign add_ln703_12_fu_1088_p2 = (add_ln703_44_fu_1082_p2 + p_Result_1_11_fu_1048_p4);

assign add_ln703_13_fu_1154_p2 = (add_ln703_45_fu_1148_p2 + p_Result_1_12_fu_1114_p4);

assign add_ln703_14_fu_1220_p2 = (add_ln703_46_fu_1214_p2 + p_Result_1_13_fu_1180_p4);

assign add_ln703_15_fu_1286_p2 = (add_ln703_47_fu_1280_p2 + p_Result_1_14_fu_1246_p4);

assign add_ln703_16_fu_1352_p2 = (add_ln703_48_fu_1346_p2 + p_Result_1_15_fu_1312_p4);

assign add_ln703_17_fu_1418_p2 = (add_ln703_49_fu_1412_p2 + p_Result_1_16_fu_1378_p4);

assign add_ln703_18_fu_1484_p2 = (add_ln703_50_fu_1478_p2 + p_Result_1_17_fu_1444_p4);

assign add_ln703_19_fu_1550_p2 = (add_ln703_51_fu_1544_p2 + p_Result_1_18_fu_1510_p4);

assign add_ln703_1_fu_362_p2 = (add_ln703_33_fu_356_p2 + p_Result_1_1_fu_322_p4);

assign add_ln703_20_fu_1616_p2 = (add_ln703_52_fu_1610_p2 + p_Result_1_19_fu_1576_p4);

assign add_ln703_21_fu_1682_p2 = (add_ln703_53_fu_1676_p2 + p_Result_1_20_fu_1642_p4);

assign add_ln703_22_fu_1748_p2 = (add_ln703_54_fu_1742_p2 + p_Result_1_21_fu_1708_p4);

assign add_ln703_23_fu_1814_p2 = (add_ln703_55_fu_1808_p2 + p_Result_1_22_fu_1774_p4);

assign add_ln703_24_fu_1880_p2 = (add_ln703_56_fu_1874_p2 + p_Result_1_23_fu_1840_p4);

assign add_ln703_25_fu_1946_p2 = (add_ln703_57_fu_1940_p2 + p_Result_1_24_fu_1906_p4);

assign add_ln703_26_fu_2012_p2 = (add_ln703_58_fu_2006_p2 + p_Result_1_25_fu_1972_p4);

assign add_ln703_27_fu_2078_p2 = (add_ln703_59_fu_2072_p2 + p_Result_1_26_fu_2038_p4);

assign add_ln703_28_fu_2144_p2 = (add_ln703_60_fu_2138_p2 + p_Result_1_27_fu_2104_p4);

assign add_ln703_29_fu_2210_p2 = (add_ln703_61_fu_2204_p2 + p_Result_1_28_fu_2170_p4);

assign add_ln703_2_fu_428_p2 = (add_ln703_34_fu_422_p2 + p_Result_1_2_fu_388_p4);

assign add_ln703_30_fu_2276_p2 = (add_ln703_62_fu_2270_p2 + p_Result_1_29_fu_2236_p4);

assign add_ln703_31_fu_2342_p2 = (add_ln703_63_fu_2336_p2 + p_Result_1_30_fu_2302_p4);

assign add_ln703_32_fu_290_p2 = (4'd2 + trunc_ln647_fu_258_p1);

assign add_ln703_33_fu_356_p2 = (4'd2 + p_Result_s_fu_312_p4);

assign add_ln703_34_fu_422_p2 = (4'd2 + p_Result_4_fu_378_p4);

assign add_ln703_35_fu_488_p2 = (4'd2 + p_Result_3_fu_444_p4);

assign add_ln703_36_fu_554_p2 = (4'd2 + p_Result_2_fu_510_p4);

assign add_ln703_37_fu_620_p2 = (4'd2 + p_Result_5_fu_576_p4);

assign add_ln703_38_fu_686_p2 = (4'd2 + p_Result_6_fu_642_p4);

assign add_ln703_39_fu_752_p2 = (4'd2 + p_Result_7_fu_708_p4);

assign add_ln703_3_fu_494_p2 = (add_ln703_35_fu_488_p2 + p_Result_1_3_fu_454_p4);

assign add_ln703_40_fu_818_p2 = (4'd2 + p_Result_8_fu_774_p4);

assign add_ln703_41_fu_884_p2 = (4'd2 + p_Result_9_fu_840_p4);

assign add_ln703_42_fu_950_p2 = (4'd2 + p_Result_1_fu_906_p4);

assign add_ln703_43_fu_1016_p2 = (4'd2 + p_Result_10_fu_972_p4);

assign add_ln703_44_fu_1082_p2 = (4'd2 + p_Result_11_fu_1038_p4);

assign add_ln703_45_fu_1148_p2 = (4'd2 + p_Result_12_fu_1104_p4);

assign add_ln703_46_fu_1214_p2 = (4'd2 + p_Result_13_fu_1170_p4);

assign add_ln703_47_fu_1280_p2 = (4'd2 + p_Result_14_fu_1236_p4);

assign add_ln703_48_fu_1346_p2 = (4'd2 + p_Result_15_fu_1302_p4);

assign add_ln703_49_fu_1412_p2 = (4'd2 + p_Result_16_fu_1368_p4);

assign add_ln703_4_fu_560_p2 = (add_ln703_36_fu_554_p2 + p_Result_1_4_fu_520_p4);

assign add_ln703_50_fu_1478_p2 = (4'd2 + p_Result_17_fu_1434_p4);

assign add_ln703_51_fu_1544_p2 = (4'd2 + p_Result_18_fu_1500_p4);

assign add_ln703_52_fu_1610_p2 = (4'd2 + p_Result_19_fu_1566_p4);

assign add_ln703_53_fu_1676_p2 = (4'd2 + p_Result_20_fu_1632_p4);

assign add_ln703_54_fu_1742_p2 = (4'd2 + p_Result_21_fu_1698_p4);

assign add_ln703_55_fu_1808_p2 = (4'd2 + p_Result_22_fu_1764_p4);

assign add_ln703_56_fu_1874_p2 = (4'd2 + p_Result_23_fu_1830_p4);

assign add_ln703_57_fu_1940_p2 = (4'd2 + p_Result_24_fu_1896_p4);

assign add_ln703_58_fu_2006_p2 = (4'd2 + p_Result_25_fu_1962_p4);

assign add_ln703_59_fu_2072_p2 = (4'd2 + p_Result_26_fu_2028_p4);

assign add_ln703_5_fu_626_p2 = (add_ln703_37_fu_620_p2 + p_Result_1_5_fu_586_p4);

assign add_ln703_60_fu_2138_p2 = (4'd2 + p_Result_27_fu_2094_p4);

assign add_ln703_61_fu_2204_p2 = (4'd2 + p_Result_28_fu_2160_p4);

assign add_ln703_62_fu_2270_p2 = (4'd2 + p_Result_29_fu_2226_p4);

assign add_ln703_63_fu_2336_p2 = (4'd2 + p_Result_30_fu_2292_p4);

assign add_ln703_6_fu_692_p2 = (add_ln703_38_fu_686_p2 + p_Result_1_6_fu_652_p4);

assign add_ln703_7_fu_758_p2 = (add_ln703_39_fu_752_p2 + p_Result_1_7_fu_718_p4);

assign add_ln703_8_fu_824_p2 = (add_ln703_40_fu_818_p2 + p_Result_1_8_fu_784_p4);

assign add_ln703_9_fu_890_p2 = (add_ln703_41_fu_884_p2 + p_Result_1_9_fu_850_p4);

assign add_ln703_fu_296_p2 = (add_ln703_32_fu_290_p2 + trunc_ln647_1_fu_262_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((icmp_ln675_reg_2811_pp0_iter1_reg == 1'd0) & (out_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln675_reg_2811 == 1'd0) & (in2_V_V_empty_n == 1'b0)) | ((icmp_ln675_reg_2811 == 1'd0) & (in1_V_V_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((icmp_ln675_reg_2811_pp0_iter1_reg == 1'd0) & (out_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln675_reg_2811 == 1'd0) & (in2_V_V_empty_n == 1'b0)) | ((icmp_ln675_reg_2811 == 1'd0) & (in1_V_V_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((icmp_ln675_reg_2811_pp0_iter1_reg == 1'd0) & (out_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln675_reg_2811 == 1'd0) & (in2_V_V_empty_n == 1'b0)) | ((icmp_ln675_reg_2811 == 1'd0) & (in1_V_V_empty_n == 1'b0)))));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (((icmp_ln675_reg_2811 == 1'd0) & (in2_V_V_empty_n == 1'b0)) | ((icmp_ln675_reg_2811 == 1'd0) & (in1_V_V_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter2 = ((icmp_ln675_reg_2811_pp0_iter1_reg == 1'd0) & (out_V_V_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign i_fu_252_p2 = (i_0_reg_235 + 3'd1);

assign icmp_ln675_fu_246_p2 = ((i_0_reg_235 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln785_10_fu_2478_p2 = ((tmp_10_reg_2925 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln785_11_fu_2490_p2 = ((tmp_11_reg_2935 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln785_12_fu_2502_p2 = ((tmp_12_reg_2945 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln785_13_fu_2514_p2 = ((tmp_13_reg_2955 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln785_14_fu_2526_p2 = ((tmp_14_reg_2965 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln785_15_fu_2538_p2 = ((tmp_15_reg_2975 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln785_16_fu_2550_p2 = ((tmp_16_reg_2985 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln785_17_fu_2562_p2 = ((tmp_17_reg_2995 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln785_18_fu_2574_p2 = ((tmp_18_reg_3005 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln785_19_fu_2586_p2 = ((tmp_19_reg_3015 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln785_1_fu_2370_p2 = ((tmp_2_reg_2835 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln785_20_fu_2598_p2 = ((tmp_20_reg_3025 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln785_21_fu_2610_p2 = ((tmp_21_reg_3035 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln785_22_fu_2622_p2 = ((tmp_22_reg_3045 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln785_23_fu_2634_p2 = ((tmp_23_reg_3055 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln785_24_fu_2646_p2 = ((tmp_24_reg_3065 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln785_25_fu_2658_p2 = ((tmp_25_reg_3075 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln785_26_fu_2670_p2 = ((tmp_26_reg_3085 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln785_27_fu_2682_p2 = ((tmp_27_reg_3095 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln785_28_fu_2694_p2 = ((tmp_28_reg_3105 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln785_29_fu_2706_p2 = ((tmp_29_reg_3115 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln785_2_fu_2382_p2 = ((tmp_3_reg_2845 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln785_30_fu_2718_p2 = ((tmp_30_reg_3125 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln785_31_fu_2730_p2 = ((tmp_31_reg_3135 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln785_3_fu_2394_p2 = ((tmp_4_reg_2855 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln785_4_fu_2406_p2 = ((tmp_5_reg_2865 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln785_5_fu_2418_p2 = ((tmp_6_reg_2875 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln785_6_fu_2430_p2 = ((tmp_7_reg_2885 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln785_7_fu_2442_p2 = ((tmp_8_reg_2895 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln785_8_fu_2454_p2 = ((tmp_9_reg_2905 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln785_9_fu_2466_p2 = ((tmp_s_reg_2915 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln785_fu_2358_p2 = ((tmp_1_reg_2825 != 2'd0) ? 1'b1 : 1'b0);

assign out_V_V_din = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{select_ln340_31_fu_2735_p3}, {select_ln340_30_fu_2723_p3}}, {select_ln340_29_fu_2711_p3}}, {select_ln340_28_fu_2699_p3}}, {select_ln340_27_fu_2687_p3}}, {select_ln340_26_fu_2675_p3}}, {select_ln340_25_fu_2663_p3}}, {select_ln340_24_fu_2651_p3}}, {select_ln340_23_fu_2639_p3}}, {select_ln340_22_fu_2627_p3}}, {select_ln340_21_fu_2615_p3}}, {select_ln340_20_fu_2603_p3}}, {select_ln340_19_fu_2591_p3}}, {select_ln340_18_fu_2579_p3}}, {select_ln340_17_fu_2567_p3}}, {select_ln340_16_fu_2555_p3}}, {select_ln340_15_fu_2543_p3}}, {select_ln340_14_fu_2531_p3}}, {select_ln340_13_fu_2519_p3}}, {select_ln340_12_fu_2507_p3}}, {select_ln340_11_fu_2495_p3}}, {select_ln340_10_fu_2483_p3}}, {select_ln340_9_fu_2471_p3}}, {select_ln340_8_fu_2459_p3}}, {select_ln340_7_fu_2447_p3}}, {select_ln340_6_fu_2435_p3}}, {select_ln340_5_fu_2423_p3}}, {select_ln340_4_fu_2411_p3}}, {select_ln340_3_fu_2399_p3}}, {select_ln340_2_fu_2387_p3}}, {select_ln340_1_fu_2375_p3}}, {select_ln340_fu_2363_p3}};

assign p_Result_10_fu_972_p4 = {{in1_V_V_dout[47:44]}};

assign p_Result_11_fu_1038_p4 = {{in1_V_V_dout[51:48]}};

assign p_Result_12_fu_1104_p4 = {{in1_V_V_dout[55:52]}};

assign p_Result_13_fu_1170_p4 = {{in1_V_V_dout[59:56]}};

assign p_Result_14_fu_1236_p4 = {{in1_V_V_dout[63:60]}};

assign p_Result_15_fu_1302_p4 = {{in1_V_V_dout[67:64]}};

assign p_Result_16_fu_1368_p4 = {{in1_V_V_dout[71:68]}};

assign p_Result_17_fu_1434_p4 = {{in1_V_V_dout[75:72]}};

assign p_Result_18_fu_1500_p4 = {{in1_V_V_dout[79:76]}};

assign p_Result_19_fu_1566_p4 = {{in1_V_V_dout[83:80]}};

assign p_Result_1_10_fu_982_p4 = {{in2_V_V_dout[47:44]}};

assign p_Result_1_11_fu_1048_p4 = {{in2_V_V_dout[51:48]}};

assign p_Result_1_12_fu_1114_p4 = {{in2_V_V_dout[55:52]}};

assign p_Result_1_13_fu_1180_p4 = {{in2_V_V_dout[59:56]}};

assign p_Result_1_14_fu_1246_p4 = {{in2_V_V_dout[63:60]}};

assign p_Result_1_15_fu_1312_p4 = {{in2_V_V_dout[67:64]}};

assign p_Result_1_16_fu_1378_p4 = {{in2_V_V_dout[71:68]}};

assign p_Result_1_17_fu_1444_p4 = {{in2_V_V_dout[75:72]}};

assign p_Result_1_18_fu_1510_p4 = {{in2_V_V_dout[79:76]}};

assign p_Result_1_19_fu_1576_p4 = {{in2_V_V_dout[83:80]}};

assign p_Result_1_1_fu_322_p4 = {{in2_V_V_dout[7:4]}};

assign p_Result_1_20_fu_1642_p4 = {{in2_V_V_dout[87:84]}};

assign p_Result_1_21_fu_1708_p4 = {{in2_V_V_dout[91:88]}};

assign p_Result_1_22_fu_1774_p4 = {{in2_V_V_dout[95:92]}};

assign p_Result_1_23_fu_1840_p4 = {{in2_V_V_dout[99:96]}};

assign p_Result_1_24_fu_1906_p4 = {{in2_V_V_dout[103:100]}};

assign p_Result_1_25_fu_1972_p4 = {{in2_V_V_dout[107:104]}};

assign p_Result_1_26_fu_2038_p4 = {{in2_V_V_dout[111:108]}};

assign p_Result_1_27_fu_2104_p4 = {{in2_V_V_dout[115:112]}};

assign p_Result_1_28_fu_2170_p4 = {{in2_V_V_dout[119:116]}};

assign p_Result_1_29_fu_2236_p4 = {{in2_V_V_dout[123:120]}};

assign p_Result_1_2_fu_388_p4 = {{in2_V_V_dout[11:8]}};

assign p_Result_1_30_fu_2302_p4 = {{in2_V_V_dout[127:124]}};

assign p_Result_1_3_fu_454_p4 = {{in2_V_V_dout[15:12]}};

assign p_Result_1_4_fu_520_p4 = {{in2_V_V_dout[19:16]}};

assign p_Result_1_5_fu_586_p4 = {{in2_V_V_dout[23:20]}};

assign p_Result_1_6_fu_652_p4 = {{in2_V_V_dout[27:24]}};

assign p_Result_1_7_fu_718_p4 = {{in2_V_V_dout[31:28]}};

assign p_Result_1_8_fu_784_p4 = {{in2_V_V_dout[35:32]}};

assign p_Result_1_9_fu_850_p4 = {{in2_V_V_dout[39:36]}};

assign p_Result_1_fu_906_p4 = {{in1_V_V_dout[43:40]}};

assign p_Result_1_s_fu_916_p4 = {{in2_V_V_dout[43:40]}};

assign p_Result_20_fu_1632_p4 = {{in1_V_V_dout[87:84]}};

assign p_Result_21_fu_1698_p4 = {{in1_V_V_dout[91:88]}};

assign p_Result_22_fu_1764_p4 = {{in1_V_V_dout[95:92]}};

assign p_Result_23_fu_1830_p4 = {{in1_V_V_dout[99:96]}};

assign p_Result_24_fu_1896_p4 = {{in1_V_V_dout[103:100]}};

assign p_Result_25_fu_1962_p4 = {{in1_V_V_dout[107:104]}};

assign p_Result_26_fu_2028_p4 = {{in1_V_V_dout[111:108]}};

assign p_Result_27_fu_2094_p4 = {{in1_V_V_dout[115:112]}};

assign p_Result_28_fu_2160_p4 = {{in1_V_V_dout[119:116]}};

assign p_Result_29_fu_2226_p4 = {{in1_V_V_dout[123:120]}};

assign p_Result_2_fu_510_p4 = {{in1_V_V_dout[19:16]}};

assign p_Result_30_fu_2292_p4 = {{in1_V_V_dout[127:124]}};

assign p_Result_3_fu_444_p4 = {{in1_V_V_dout[15:12]}};

assign p_Result_4_fu_378_p4 = {{in1_V_V_dout[11:8]}};

assign p_Result_5_fu_576_p4 = {{in1_V_V_dout[23:20]}};

assign p_Result_6_fu_642_p4 = {{in1_V_V_dout[27:24]}};

assign p_Result_7_fu_708_p4 = {{in1_V_V_dout[31:28]}};

assign p_Result_8_fu_774_p4 = {{in1_V_V_dout[35:32]}};

assign p_Result_9_fu_840_p4 = {{in1_V_V_dout[39:36]}};

assign p_Result_s_fu_312_p4 = {{in1_V_V_dout[7:4]}};

assign select_ln340_10_fu_2483_p3 = ((icmp_ln785_10_fu_2478_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_10_reg_2920);

assign select_ln340_11_fu_2495_p3 = ((icmp_ln785_11_fu_2490_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_11_reg_2930);

assign select_ln340_12_fu_2507_p3 = ((icmp_ln785_12_fu_2502_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_12_reg_2940);

assign select_ln340_13_fu_2519_p3 = ((icmp_ln785_13_fu_2514_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_13_reg_2950);

assign select_ln340_14_fu_2531_p3 = ((icmp_ln785_14_fu_2526_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_14_reg_2960);

assign select_ln340_15_fu_2543_p3 = ((icmp_ln785_15_fu_2538_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_15_reg_2970);

assign select_ln340_16_fu_2555_p3 = ((icmp_ln785_16_fu_2550_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_16_reg_2980);

assign select_ln340_17_fu_2567_p3 = ((icmp_ln785_17_fu_2562_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_17_reg_2990);

assign select_ln340_18_fu_2579_p3 = ((icmp_ln785_18_fu_2574_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_18_reg_3000);

assign select_ln340_19_fu_2591_p3 = ((icmp_ln785_19_fu_2586_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_19_reg_3010);

assign select_ln340_1_fu_2375_p3 = ((icmp_ln785_1_fu_2370_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_1_reg_2830);

assign select_ln340_20_fu_2603_p3 = ((icmp_ln785_20_fu_2598_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_20_reg_3020);

assign select_ln340_21_fu_2615_p3 = ((icmp_ln785_21_fu_2610_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_21_reg_3030);

assign select_ln340_22_fu_2627_p3 = ((icmp_ln785_22_fu_2622_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_22_reg_3040);

assign select_ln340_23_fu_2639_p3 = ((icmp_ln785_23_fu_2634_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_23_reg_3050);

assign select_ln340_24_fu_2651_p3 = ((icmp_ln785_24_fu_2646_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_24_reg_3060);

assign select_ln340_25_fu_2663_p3 = ((icmp_ln785_25_fu_2658_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_25_reg_3070);

assign select_ln340_26_fu_2675_p3 = ((icmp_ln785_26_fu_2670_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_26_reg_3080);

assign select_ln340_27_fu_2687_p3 = ((icmp_ln785_27_fu_2682_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_27_reg_3090);

assign select_ln340_28_fu_2699_p3 = ((icmp_ln785_28_fu_2694_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_28_reg_3100);

assign select_ln340_29_fu_2711_p3 = ((icmp_ln785_29_fu_2706_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_29_reg_3110);

assign select_ln340_2_fu_2387_p3 = ((icmp_ln785_2_fu_2382_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_2_reg_2840);

assign select_ln340_30_fu_2723_p3 = ((icmp_ln785_30_fu_2718_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_30_reg_3120);

assign select_ln340_31_fu_2735_p3 = ((icmp_ln785_31_fu_2730_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_31_reg_3130);

assign select_ln340_3_fu_2399_p3 = ((icmp_ln785_3_fu_2394_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_3_reg_2850);

assign select_ln340_4_fu_2411_p3 = ((icmp_ln785_4_fu_2406_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_4_reg_2860);

assign select_ln340_5_fu_2423_p3 = ((icmp_ln785_5_fu_2418_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_5_reg_2870);

assign select_ln340_6_fu_2435_p3 = ((icmp_ln785_6_fu_2430_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_6_reg_2880);

assign select_ln340_7_fu_2447_p3 = ((icmp_ln785_7_fu_2442_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_7_reg_2890);

assign select_ln340_8_fu_2459_p3 = ((icmp_ln785_8_fu_2454_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_8_reg_2900);

assign select_ln340_9_fu_2471_p3 = ((icmp_ln785_9_fu_2466_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_9_reg_2910);

assign select_ln340_fu_2363_p3 = ((icmp_ln785_fu_2358_p2[0:0] === 1'b1) ? 4'd15 : add_ln703_reg_2820);

assign trunc_ln647_1_fu_262_p1 = in2_V_V_dout[3:0];

assign trunc_ln647_fu_258_p1 = in1_V_V_dout[3:0];

assign zext_ln1353_10_fu_940_p1 = add_ln1353_20_fu_934_p2;

assign zext_ln1353_11_fu_1006_p1 = add_ln1353_22_fu_1000_p2;

assign zext_ln1353_12_fu_1072_p1 = add_ln1353_24_fu_1066_p2;

assign zext_ln1353_13_fu_1138_p1 = add_ln1353_26_fu_1132_p2;

assign zext_ln1353_14_fu_1204_p1 = add_ln1353_28_fu_1198_p2;

assign zext_ln1353_15_fu_1270_p1 = add_ln1353_30_fu_1264_p2;

assign zext_ln1353_16_fu_1336_p1 = add_ln1353_32_fu_1330_p2;

assign zext_ln1353_17_fu_1402_p1 = add_ln1353_34_fu_1396_p2;

assign zext_ln1353_18_fu_1468_p1 = add_ln1353_36_fu_1462_p2;

assign zext_ln1353_19_fu_1534_p1 = add_ln1353_38_fu_1528_p2;

assign zext_ln1353_1_fu_346_p1 = add_ln1353_2_fu_340_p2;

assign zext_ln1353_20_fu_1600_p1 = add_ln1353_40_fu_1594_p2;

assign zext_ln1353_21_fu_1666_p1 = add_ln1353_42_fu_1660_p2;

assign zext_ln1353_22_fu_1732_p1 = add_ln1353_44_fu_1726_p2;

assign zext_ln1353_23_fu_1798_p1 = add_ln1353_46_fu_1792_p2;

assign zext_ln1353_24_fu_1864_p1 = add_ln1353_48_fu_1858_p2;

assign zext_ln1353_25_fu_1930_p1 = add_ln1353_50_fu_1924_p2;

assign zext_ln1353_26_fu_1996_p1 = add_ln1353_52_fu_1990_p2;

assign zext_ln1353_27_fu_2062_p1 = add_ln1353_54_fu_2056_p2;

assign zext_ln1353_28_fu_2128_p1 = add_ln1353_56_fu_2122_p2;

assign zext_ln1353_29_fu_2194_p1 = add_ln1353_58_fu_2188_p2;

assign zext_ln1353_2_fu_412_p1 = add_ln1353_4_fu_406_p2;

assign zext_ln1353_30_fu_2260_p1 = add_ln1353_60_fu_2254_p2;

assign zext_ln1353_31_fu_2326_p1 = add_ln1353_62_fu_2320_p2;

assign zext_ln1353_3_fu_478_p1 = add_ln1353_6_fu_472_p2;

assign zext_ln1353_4_fu_544_p1 = add_ln1353_8_fu_538_p2;

assign zext_ln1353_5_fu_610_p1 = add_ln1353_10_fu_604_p2;

assign zext_ln1353_6_fu_676_p1 = add_ln1353_12_fu_670_p2;

assign zext_ln1353_7_fu_742_p1 = add_ln1353_14_fu_736_p2;

assign zext_ln1353_8_fu_808_p1 = add_ln1353_16_fu_802_p2;

assign zext_ln1353_9_fu_874_p1 = add_ln1353_18_fu_868_p2;

assign zext_ln1353_fu_280_p1 = add_ln1353_fu_274_p2;

assign zext_ln215_10_fu_596_p1 = p_Result_5_fu_576_p4;

assign zext_ln215_11_fu_600_p1 = p_Result_1_5_fu_586_p4;

assign zext_ln215_12_fu_662_p1 = p_Result_6_fu_642_p4;

assign zext_ln215_13_fu_666_p1 = p_Result_1_6_fu_652_p4;

assign zext_ln215_14_fu_728_p1 = p_Result_7_fu_708_p4;

assign zext_ln215_15_fu_732_p1 = p_Result_1_7_fu_718_p4;

assign zext_ln215_16_fu_794_p1 = p_Result_8_fu_774_p4;

assign zext_ln215_17_fu_798_p1 = p_Result_1_8_fu_784_p4;

assign zext_ln215_18_fu_860_p1 = p_Result_9_fu_840_p4;

assign zext_ln215_19_fu_864_p1 = p_Result_1_9_fu_850_p4;

assign zext_ln215_1_fu_270_p1 = trunc_ln647_1_fu_262_p1;

assign zext_ln215_20_fu_926_p1 = p_Result_1_fu_906_p4;

assign zext_ln215_21_fu_930_p1 = p_Result_1_s_fu_916_p4;

assign zext_ln215_22_fu_992_p1 = p_Result_10_fu_972_p4;

assign zext_ln215_23_fu_996_p1 = p_Result_1_10_fu_982_p4;

assign zext_ln215_24_fu_1058_p1 = p_Result_11_fu_1038_p4;

assign zext_ln215_25_fu_1062_p1 = p_Result_1_11_fu_1048_p4;

assign zext_ln215_26_fu_1124_p1 = p_Result_12_fu_1104_p4;

assign zext_ln215_27_fu_1128_p1 = p_Result_1_12_fu_1114_p4;

assign zext_ln215_28_fu_1190_p1 = p_Result_13_fu_1170_p4;

assign zext_ln215_29_fu_1194_p1 = p_Result_1_13_fu_1180_p4;

assign zext_ln215_2_fu_332_p1 = p_Result_s_fu_312_p4;

assign zext_ln215_30_fu_1256_p1 = p_Result_14_fu_1236_p4;

assign zext_ln215_31_fu_1260_p1 = p_Result_1_14_fu_1246_p4;

assign zext_ln215_32_fu_1322_p1 = p_Result_15_fu_1302_p4;

assign zext_ln215_33_fu_1326_p1 = p_Result_1_15_fu_1312_p4;

assign zext_ln215_34_fu_1388_p1 = p_Result_16_fu_1368_p4;

assign zext_ln215_35_fu_1392_p1 = p_Result_1_16_fu_1378_p4;

assign zext_ln215_36_fu_1454_p1 = p_Result_17_fu_1434_p4;

assign zext_ln215_37_fu_1458_p1 = p_Result_1_17_fu_1444_p4;

assign zext_ln215_38_fu_1520_p1 = p_Result_18_fu_1500_p4;

assign zext_ln215_39_fu_1524_p1 = p_Result_1_18_fu_1510_p4;

assign zext_ln215_3_fu_336_p1 = p_Result_1_1_fu_322_p4;

assign zext_ln215_40_fu_1586_p1 = p_Result_19_fu_1566_p4;

assign zext_ln215_41_fu_1590_p1 = p_Result_1_19_fu_1576_p4;

assign zext_ln215_42_fu_1652_p1 = p_Result_20_fu_1632_p4;

assign zext_ln215_43_fu_1656_p1 = p_Result_1_20_fu_1642_p4;

assign zext_ln215_44_fu_1718_p1 = p_Result_21_fu_1698_p4;

assign zext_ln215_45_fu_1722_p1 = p_Result_1_21_fu_1708_p4;

assign zext_ln215_46_fu_1784_p1 = p_Result_22_fu_1764_p4;

assign zext_ln215_47_fu_1788_p1 = p_Result_1_22_fu_1774_p4;

assign zext_ln215_48_fu_1850_p1 = p_Result_23_fu_1830_p4;

assign zext_ln215_49_fu_1854_p1 = p_Result_1_23_fu_1840_p4;

assign zext_ln215_4_fu_398_p1 = p_Result_4_fu_378_p4;

assign zext_ln215_50_fu_1916_p1 = p_Result_24_fu_1896_p4;

assign zext_ln215_51_fu_1920_p1 = p_Result_1_24_fu_1906_p4;

assign zext_ln215_52_fu_1982_p1 = p_Result_25_fu_1962_p4;

assign zext_ln215_53_fu_1986_p1 = p_Result_1_25_fu_1972_p4;

assign zext_ln215_54_fu_2048_p1 = p_Result_26_fu_2028_p4;

assign zext_ln215_55_fu_2052_p1 = p_Result_1_26_fu_2038_p4;

assign zext_ln215_56_fu_2114_p1 = p_Result_27_fu_2094_p4;

assign zext_ln215_57_fu_2118_p1 = p_Result_1_27_fu_2104_p4;

assign zext_ln215_58_fu_2180_p1 = p_Result_28_fu_2160_p4;

assign zext_ln215_59_fu_2184_p1 = p_Result_1_28_fu_2170_p4;

assign zext_ln215_5_fu_402_p1 = p_Result_1_2_fu_388_p4;

assign zext_ln215_60_fu_2246_p1 = p_Result_29_fu_2226_p4;

assign zext_ln215_61_fu_2250_p1 = p_Result_1_29_fu_2236_p4;

assign zext_ln215_62_fu_2312_p1 = p_Result_30_fu_2292_p4;

assign zext_ln215_63_fu_2316_p1 = p_Result_1_30_fu_2302_p4;

assign zext_ln215_6_fu_464_p1 = p_Result_3_fu_444_p4;

assign zext_ln215_7_fu_468_p1 = p_Result_1_3_fu_454_p4;

assign zext_ln215_8_fu_530_p1 = p_Result_2_fu_510_p4;

assign zext_ln215_9_fu_534_p1 = p_Result_1_4_fu_520_p4;

assign zext_ln215_fu_266_p1 = trunc_ln647_fu_258_p1;

endmodule //AddStreams
