#define MH 64
#define MW 27
#define SIMD 3
#define PE 8
#define INPUT_STREAM_WIDTH 4
#define WEIGHT_STREAM_WIDTH 4
#define OUTPUT_STREAM_WIDTH 4
#define TW ap_uint<2>
#define TSrcI Slice<ap_uint<2>>
#define TDstI Slice<ap_uint<16>>
#define TWeightsI Slice<ap_uint<2>>
#define REPS 50
#define W_BITS 2
#define INPUT_BITS 2
